[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/test-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 15 