[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/api-docs"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 